import path from 'node:path';
import fs from 'node:fs/promises';

/**
 * CSS 사이드 이펙트(예: `variables.css`)를 패키지의 `sideEffects`로 노출하는 구조에서,
 * TypeScript가 해당 CSS 엔트리/출력 디렉터리를 “타입 루트로 인식”하거나
 * 번들러/툴링이 `.d.ts` 존재를 기대하는 경우를 대비해 빈 선언 파일(`index.d.ts`)을 생성한다.
 *
 * @param args - 출력 디렉터리 절대 경로를 담는 인자
 * @param args.outputDirAbs - `index.d.ts`를 생성할 출력 디렉터리의 절대 경로
 */
export const writeCssSideEffectTypes = async (args: { outputDirAbs: string }): Promise<void> => {
  const outDir = path.join(args.outputDirAbs);
  const outFile = path.join(outDir, 'index.d.ts');

  await fs.mkdir(outDir, { recursive: true });

  const content = `// AUTO-GENERATED by src/build.ts
export {};
`;

  await fs.writeFile(outFile, content, 'utf8');
};
