export const selectClasses = {
  root: 'ui-select',
  trigger: 'ui-select__trigger',
  value: 'ui-select__value',
  placeholder: 'ui-select__placeholder',
  icon: 'ui-select__icon',
  hiddenInput: 'ui-select__native-input',
  listbox: 'ui-select__listbox',
  option: 'ui-select__option',
  optionSelected: 'ui-select__option--selected',
  optionHighlighted: 'ui-select__option--highlighted',
  open: 'ui-select--open',
  focused: 'ui-select--focused',
  disabled: 'ui-select--disabled',
  error: 'ui-select--error',
  multiple: 'ui-select--multiple',
  fullWidth: 'ui-select--fullWidth',
  sizeSm: 'ui-select--size-sm',
  sizeMd: 'ui-select--size-md',
  variantPlain: 'ui-select--variant-plain',
  variantFilled: 'ui-select--variant-filled',
  variantBoxed: 'ui-select--variant-boxed',
  colorPrimary: 'ui-select--color-primary',
  colorSecondary: 'ui-select--color-secondary',
} as const;
