import type { Format, TransformedToken } from 'style-dictionary/types';

import type { ThemeName } from '../../types';
import { mapTokenPath } from '../utils';

type ThemeTokensOptions = { theme?: ThemeName };

type MutableRecord = Record<string, unknown>;

type ThemeTokensOut = {
  color: MutableRecord;
  spacing: MutableRecord;
  radius: MutableRecord;
  borderWidth: MutableRecord;
  border: MutableRecord;
  typography: MutableRecord;
  shadow: MutableRecord;
  elevation: MutableRecord;
  component: MutableRecord;
};

const isRecord = (v: unknown): v is MutableRecord => {
  return !!v && typeof v === 'object' && !Array.isArray(v);
};

/**
 * 주어진 객체에 대해 `path`(키 배열) 위치에 값을 "깊게" 설정합니다.
 *
 * 예:
 * - path: ["color", "primary", "pr500"]
 * - value: "#2E90FA"
 *
 * 결과:
 * ```ts
 * obj.color.primary.pr500 = "#2E90FA"
 * ```
 *
 * @param obj 값을 설정할 대상 객체
 * @param path 키 경로 배열
 * @param value 설정할 값
 */

const setDeep = (obj: MutableRecord, path: readonly string[], value: unknown) => {
  if (path.length === 0) return;

  let cur: MutableRecord = obj;

  for (let i = 0; i < path.length - 1; i++) {
    const k = path[i];
    if (!k) return;

    const existing = cur[k];
    if (!isRecord(existing)) cur[k] = {};
    cur = cur[k] as MutableRecord;
  }

  const last = path[path.length - 1];
  if (!last) return;
  cur[last] = value;
};

/**
 * Style Dictionary 커스텀 포맷: 테마별 TypeScript 토큰 모듈을 생성합니다.
 */
export const tsThemeTokensFormat: Format = {
  name: 'ds/ts/theme-tokens',
  format: ({ dictionary, options }) => {
    const opt = (options ?? {}) as ThemeTokensOptions;
    const theme = opt.theme ?? 'global';

    const tokens = [...dictionary.allTokens] as TransformedToken[];
    tokens.sort((a, b) => a.path.join('.').localeCompare(b.path.join('.')));

    const root: ThemeTokensOut = {
      color: {},
      spacing: {},
      radius: {},
      borderWidth: {},
      border: {},
      typography: {},
      shadow: {},
      elevation: {},
      component: {},
    };

    for (const t of tokens) {
      const destPath = mapTokenPath({
        path: t.path,
        type: (t as { type?: string }).type,
        $type: (t as { $type?: string }).$type,
        original: (t as { original?: { type?: string; $type?: string } }).original,
      });
      setDeep(root as unknown as MutableRecord, destPath, t.value as unknown);
    }

    const json = JSON.stringify(root, null, 2);

    return `/* eslint-disable */
// AUTO-GENERATED by Style Dictionary
// theme: ${theme}

export const tokens = ${json} as const;

export type Tokens = typeof tokens;

// 그룹 타입(원하신 형태로 바로 꺼내쓰기)
export type ColorTokens = Tokens['color'];
export type SpacingTokens = Tokens['spacing'];
export type RadiusTokens = Tokens['radius'];
export type BorderWidthTokens = Tokens['borderWidth'];
export type BorderTokens = Tokens['border'];
export type TypographyTokens = Tokens['typography'];
export type ShadowTokens = Tokens['shadow'];
export type ElevationTokens = Tokens['elevation'];
export type ComponentTokens = Tokens['component'];

export type ThemeTokens = {
  color: ColorTokens;
  spacing: SpacingTokens;
  radius: RadiusTokens;
  borderWidth: BorderWidthTokens;
  border: BorderTokens;
  typography: TypographyTokens;
  shadow: ShadowTokens;
  elevation: ElevationTokens;
  component: ComponentTokens;
};
`;
  },
};
