import type { Format } from 'style-dictionary/types';
import { mapTokenPath } from '../utils';

/**
 * 주어진 객체에 대해 `path`(키 배열) 위치에 값을 "깊게" 설정합니다.
 *
 * 예:
 * - path: ["color", "primary", "pr500"]
 * - value: "#2E90FA"
 *
 * 결과:
 * ```ts
 * obj.color.primary.pr500 = "#2E90FA"
 * ```
 *
 * @param obj 값을 설정할 대상 객체
 * @param path 키 경로 배열
 * @param value 설정할 값
 */
const setDeep = (obj: any, path: string[], value: any) => {
  let cur = obj;
  for (let i = 0; i < path.length - 1; i++) {
    const k = path[i]!;
    cur[k] ??= {};
    cur = cur[k];
  }
  cur[path[path.length - 1]!] = value;
};

/**
 * Style Dictionary 커스텀 포맷: 테마별 TypeScript 토큰 모듈을 생성합니다.
 */
export const tsThemeTokensFormat: Format = {
  name: 'ds/ts/theme-tokens',
  format: ({ dictionary, options }) => {
    const theme = (options as any)?.theme ?? 'unknown';

    const tokens = [...dictionary.allTokens] as any[];
    tokens.sort((a, b) => a.path.join('.').localeCompare(b.path.join('.')));

    const root: any = {
      color: {},
      spacing: {},
      radius: {},
      borderWidth: {},
      border: {},
      typography: {},
      shadow: {},
      elevation: {},
      component: {},
    };

    for (const t of tokens) {
      const destPath = mapTokenPath(t);
      setDeep(root, destPath, t.value);
    }

    const json = JSON.stringify(root, null, 2);

    return `/* eslint-disable */
// AUTO-GENERATED by Style Dictionary
// theme: ${theme}

export const tokens = ${json} as const;

export type Tokens = typeof tokens;
`;
  },
};
