export const inputBaseClasses = {
  root: 'ui-input-base',
  formControl: 'ui-input-base--form-control',
  input: 'ui-input-base__input',
  focused: 'ui-input-base--focused',
  disabled: 'ui-input-base--disabled',
  error: 'ui-input-base--error',
  fullWidth: 'ui-input-base--fullWidth',
  multiline: 'ui-input-base--multiline',
  adornedStart: 'ui-input-base--adorned-start',
  adornedEnd: 'ui-input-base--adorned-end',
  readOnly: 'ui-input-base--read-only',
  sizeSm: 'ui-input-base--size-sm',
  sizeMd: 'ui-input-base--size-md',
  inputSizeSm: 'ui-input-base__input--size-sm',
  inputHiddenLabel: 'ui-input-base__input--hidden-label',
  colorPrimary: 'ui-input-base--color-primary',
  colorSecondary: 'ui-input-base--color-secondary',
  startAdornment: 'ui-input-base__start-adornment',
  endAdornment: 'ui-input-base__end-adornment',
} as const;
