name: Chromatic

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "libs/react-ui/**"
  push:
    branches: [main]
    paths:
      - "libs/react-ui/**"

concurrency:
  group: chromatic-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ vars.PNPM_VERSION }}

      - name: Setup Node.js (pnpm cache)
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build Libraries
        run: pnpm run build:libs:web

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: libs/react-ui/storybook-static
